const lessons = Object.freeze(
  [
    {
      number: 1,
      slug: 'html5',
      title: 'ZWA‑1 (HTML5): HTML5 prezentace s živým playgroundem',
      shortTitle: 'HTML5 a sémantika',
      moduleId: 'web-foundations',
      focus: 'Vybudujte pevný sémantický základ HTML pro každou stránku.',
      artwork: '/course-art/lesson-01-html5.svg',
      href: '/interactive-zwa-1-html5',
      componentKey: 'interactive_zwa_1_html5_presentation',
    },
    {
      number: 2,
      slug: 'forms',
      title: 'ZWA‑2 (Formuláře): Formuláře na straně klienta a HTML5 vstupy',
      shortTitle: 'Přístupné formuláře',
      moduleId: 'web-foundations',
      focus: 'Sbírejte a ověřujte vstupy uživatelů pomocí přístupných HTML formulářů.',
      artwork: '/course-art/lesson-02-forms.svg',
      href: '/interactive-zwa-2-forms',
      componentKey: 'interactive_zwa_2_forms_presentation',
    },
    {
      number: 3,
      slug: 'network',
      title: 'ZWA‑3 (Síť): Webová prezentace se simulovanou linuxovou CLI',
      shortTitle: 'Jak putuje požadavek',
      moduleId: 'web-foundations',
      focus: 'Pochopte, jak spolupracují prohlížeče, servery a HTTP.',
      artwork: '/course-art/lesson-03-network.svg',
      href: '/interactive-zwa-1/',
      componentKey: 'interactive_zwa_1_web_presentation_with_simulated_linux_cli',
    },
    {
      number: 4,
      slug: 'css',
      title: 'ZWA‑4: CSS prezentace s živým playgroundem',
      shortTitle: 'CSS a vizuální pravidla',
      moduleId: 'presentation-interaction',
      focus: 'Použijte CSS pro strukturu stránky, rytmus a vizuální hierarchii.',
      artwork: '/course-art/lesson-04-css.svg',
      href: '/interactive-zwa-2',
      componentKey: 'interactive_zwa_2_css_presentation',
    },
    {
      number: 5,
      slug: 'css-ii',
      title: 'ZWA‑5: CSS II – layout, responzivita, tisk',
      shortTitle: 'Responzivní layout',
      moduleId: 'presentation-interaction',
      focus: 'Skládejte odolné layouty, které se přizpůsobí obrazovkám i tisku.',
      artwork: '/course-art/lesson-05-css-ii.svg',
      href: '/interactive-zwa-5-css-ii',
      componentKey: 'interactive_zwa_5_css2_presentation',
    },
    {
      number: 6,
      slug: 'javascript',
      title: 'ZWA‑6: Základy JavaScriptu s živým playgroundem',
      shortTitle: 'JavaScript a události',
      moduleId: 'presentation-interaction',
      focus: 'Nechte rozhraní reagovat na události pomocí srozumitelné logiky JavaScriptu.',
      artwork: '/course-art/lesson-06-javascript.svg',
      href: '/interactive-zwa-5-js',
      componentKey: 'interactive_zwa_5_javascript_presentation',
    },
    {
      number: 7,
      slug: 'classes-ajax',
      title: 'ZWA‑7: Třídy a AJAX',
      shortTitle: 'Třídy a AJAX',
      moduleId: 'server-foundations',
      focus: 'Uspořádejte klientský a serverový kód pomocí tříd a asynchronních požadavků.',
      artwork: '/course-art/lesson-07-classes-ajax.svg',
      href: '/interactive-zwa-7',
      componentKey: 'interactive_zwa_7_classes_ajax_presentation',
    },
    {
      number: 8,
      slug: 'php',
      title: 'ZWA‑8: Základy PHP – Malý test #2',
      shortTitle: 'PHP na serveru',
      moduleId: 'server-foundations',
      focus: 'Poznejte stavební bloky PHP pro dynamické webové stránky.',
      artwork: '/course-art/lesson-08-php.svg',
      href: '/interactive-zwa-8-php',
      componentKey: 'interactive_zwa_8_php_presentation',
    },
    {
      number: 9,
      slug: 'forms-crud',
      title: 'ZWA‑9: Formuláře na serveru a CRUD',
      shortTitle: 'Formuláře a CRUD',
      moduleId: 'server-foundations',
      focus: 'Propojte serverové formuláře s operacemi vytvoření, čtení, úpravy a mazání.',
      artwork: '/course-art/lesson-09-forms-crud.svg',
      href: '/interactive-zwa-9',
      componentKey: 'interactive_zwa_9_forms_crud_presentation',
    },
    {
      number: 10,
      slug: 'sessions-cookies',
      title: 'ZWA‑10: Relace a cookies v PHP',
      shortTitle: 'Relace a cookies',
      moduleId: 'state-data',
      focus: 'Uchovávejte užitečný stav mezi požadavky pomocí relací a cookies.',
      artwork: '/course-art/lesson-10-sessions-cookies.svg',
      href: '/interactive-zwa-10-sessions-cookies',
      componentKey: 'interactive_zwa_10_sessions_cookies_presentation',
    },
    {
      number: 11,
      slug: 'files-json',
      title: 'ZWA‑11: Soubory a JSON v PHP',
      shortTitle: 'Soubory a JSON',
      moduleId: 'state-data',
      focus: 'Čtěte, zapisujte a vyměňujte strukturovaná data pomocí souborů a JSON.',
      artwork: '/course-art/lesson-11-files-json.svg',
      href: '/interactive-zwa-11-files-json',
      componentKey: 'interactive_zwa_11_files_json_presentation',
    },
    {
      number: 12,
      slug: 'auth',
      title: 'ZWA‑12: Autentizace a autorizace v PHP',
      shortTitle: 'Autentizace',
      moduleId: 'state-data',
      focus: 'Chraňte aplikaci pomocí autentizace a autorizace.',
      artwork: '/course-art/lesson-12-auth.svg',
      href: '/interactive-zwa-12-auth',
      componentKey: 'interactive_zwa_12_auth_presentation',
    },
  ].map(Object.freeze),
);

function getLessonByNumber(number) {
  return lessons.find((lesson) => lesson.number === number);
}

function getLessonBySlug(slug) {
  return lessons.find((lesson) => lesson.slug === slug);
}

export { lessons, getLessonByNumber, getLessonBySlug };
